<a href="https://colab.research.google.com/github/gmrampe/Python-for-Datascience/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
DAV -> Data Analysis and Visualization

DAV-1: Python Libraries: Numpy, Pandas, Matplotlib, Seaborn
DAV-2: Probability and Stats
DAV-3: Hypothesis Testing
'''

'\nDAV -> Data Analysis and Visualization\n\nDAV-1: Python Libraries: Numpy, Pandas, Matplotlib, Seaborn\nDAV-2: Probability and Stats\nDAV-3: Hypothesis Testing\n'

In [ ]:
import numpy as np

In [ ]:
#speed comparison

In [ ]:
lst = list(range(10000000))

In [ ]:
len(lst)

10000000

In [ ]:
%timeit [i**2 for i in lst]

3.69 s ± 552 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
b = np.array(lst)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation

In [ ]:
b = np.array([5,7,3,6])
print(b**2)

[25 49  9 36]


In [ ]:
b = np.array(lst)
%timeit b**2

35.6 ms ± 7.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

1

In [ ]:
len(b)

10000000

In [ ]:
b.shape

(10000000,)

In [ ]:
b = [1, 2.0, "AJ"]
type(b)

list

<img src="https://drive.google.com/uc?id=1lgwART77tbifHMJjw-d4NV7aEpr0LVat">

In [ ]:
c = list(range(1,10))

In [ ]:
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
type(c)

list

In [ ]:
c = np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
c = np.arange(1, 5, 0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
len(c)

8

In [ ]:
a = [1, 3, "AJ"]
type(a)

list

In [ ]:
b = np.array(a)
type(b)

numpy.ndarray

In [ ]:
print(b)

['1' '3' 'AJ']


In [ ]:
a = [5,7,3,2]
b = np.array(a)
print(b)

[5 7 3 2]


In [ ]:
c = np.array(a, dtype = "float")
print(c)

[5. 7. 3. 2.]


In [ ]:
#Quiz1

a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
a = np.array([1, 5, 8, 3])
type(a)

numpy.ndarray

In [ ]:
b = a.astype("float")
print(b)

[1. 5. 8. 3.]


<img src="https://drive.google.com/uc?id=1GSV_E1CaCc_Ur7pWJ-Kqv0VKvBRwByR1">

In [ ]:
b = np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
#indexing

In [ ]:
b[3]

3

In [ ]:
b = np.array([6,8,3,5,7,1])
print(b)

[6 8 3 5 7 1]


In [ ]:
b[4]

7

In [ ]:
b[-1]

1

In [ ]:
b[-2]

7

In [ ]:
b[-4]

3

In [ ]:
#slicing

In [ ]:
print(b)

[6 8 3 5 7 1]


In [ ]:
print(b[1:5])

[8 3 5 7]


In [ ]:
b[3:]

array([5, 7, 1])

In [ ]:
b[:4]

array([6, 8, 3, 5])

In [ ]:
#Quiz2

import numpy as np

arr = np.arange(5)
arr[2:4] = 0

print(arr)

[0 1 0 0 4]


In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr[2:4] = 0

In [ ]:
print(arr)

[0 1 0 0 4]


In [ ]:
a = np.array(["AJ", "Deepak", "Abhishek"])
c = np.array(a, dtype = "float")

ValueError: ignored

In [ ]:
#multi-indexing

In [ ]:
b = np.arange(1,15,2)
print(b)


[ 1  3  5  7  9 11 13]


In [ ]:
b[2]

5

In [ ]:
b[6]

13

In [ ]:
print(b[ [2, 6] ])

[ 5 13]


In [ ]:
print(b[[5,2,4]])

[11  5  9]


In [ ]:
#Quiz3

import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
#Fancy indexing -> Masking

In [ ]:
a = np.array([6,9,3,5,7,2,8,1])
print(a)

[6 9 3 5 7 2 8 1]


In [ ]:
#element-wise operation
a < 6

array([False, False,  True,  True, False,  True, False,  True])

In [ ]:
a[ a<6 ]

array([3, 5, 2, 1])

In [ ]:
#Filter all the even elements from a, using fancy indexing
a[a%2 == 0]

array([6, 2, 8])

In [ ]:
#Quiz4

a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]
print(a)

[1, 2, 6, 7, 8]


In [ ]:
#Quiz5

a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
b = [8,7,6]
print(b[::-2])

[6, 8]


In [ ]:
a = np.array([6,9,3,5,7,2,8,1])
print(a)

[6 9 3 5 7 2 8 1]


In [ ]:
#using fancy indexing, filter all the odd numbers in a
a[a%2 != 0]

array([9, 3, 5, 7, 1])

In [ ]:
#Case-study -> NPS

In [ ]:
#NPS -> Net Promoter Score

<img src="https://drive.google.com/uc?id=1-u8e-v_90JdikorKsKzBM-JJqoRtzsN8">

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">

In [ ]:
#NPS = %Promoters - %Detractors
'''
%promoters = #of promoters/total users
'''

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score[:10]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [ ]:
len(score)

1167

In [ ]:
p_rating = score[score > 8]
print(p_rating)

[10  9  9  9  9  9 10  9  9 10  9  9  9  9  9  9  9 10 10  9 10  9 10  9
  9 10 10  9 10  9 10 10 10  9  9 10 10 10  9 10  9 10  9  9  9 10  9  9
  9  9  9  9 10  9  9  9 10  9 10  9  9  9  9  9 10 10  9 10  9  9 10  9
  9 10  9  9  9  9  9  9  9  9  9  9  9 10  9  9  9  9  9  9  9  9 10  9
  9  9  9  9 10 10  9 10 10 10 10  9 10  9  9  9  9  9  9  9 10  9 10  9
 10  9 10 10 10  9  9 10 10  9  9  9  9 10  9  9  9  9 10 10  9  9  9 10
  9  9  9  9  9 10  9  9  9 10  9 10 10  9  9  9  9 10  9 10  9  9  9  9
 10  9 10  9  9  9  9  9  9  9  9  9  9  9 10 10  9  9  9 10  9 10 10 10
 10 10  9  9  9  9 10 10 10  9  9 10  9 10 10 10 10  9 10 10  9 10  9  9
  9  9 10  9 10  9 10  9  9  9  9 10  9  9  9  9  9 10  9 10 10  9 10 10
 10  9  9  9  9  9  9 10  9  9 10  9 10 10  9  9  9 10 10 10 10  9  9  9
 10 10  9 10  9  9  9 10  9  9  9  9  9  9  9  9  9  9 10  9  9  9 10  9
 10  9 10  9 10  9  9 10 10  9  9  9 10  9  9 10  9  9  9  9  9  9 10 10
  9 10  9  9  9  9 10  9  9  9  9 10  9 10  9 10  9

In [ ]:
no_promoters = len(p_rating)
print(no_promoters)

609


In [ ]:
total = len(score)

In [ ]:
perc_promoters = no_promoters*100/total
print(perc_promoters)

52.18508997429306


In [ ]:
d_rating = score[score < 7]
no_detractors = len(d_rating)
print(no_detractors)

332


In [ ]:
perc_detractors = no_detractors*100/total
print(perc_detractors)

28.449014567266495


In [ ]:
nps = perc_promoters - perc_detractors
print(nps)

23.73607540702656


In [ ]:
nps = np.round(nps, 2)
print(nps)

23.74
