# Numpy concept 

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\rampe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [5]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\rampe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [6]:
import numpy as np

In [7]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [9]:
#one dimensional array creation with type,dimensions,datatype,size of array,and shape
s=np.array([1,2,3])
print(s)
print(type(s))
print(s.ndim)
print(s.dtype)
print(s.size)
print(s.shape)

[1 2 3]
<class 'numpy.ndarray'>
1
int32
3
(3,)


In [10]:
#creating two dimensional arrays with shape,size and data type
s=np.array([[1,2,3],[4,5,6]])
print(s)
print(type(s))
print(s.ndim)
print(s.dtype)
print(s.size)
print(s.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
int32
6
(2, 3)


In [11]:
#creating three dimesions arrays
s=np.array([[[1,2,3]]])
print(s)
print(type(s))
print(s.ndim)
print(s.dtype)
print(s.size)
print(s.shape)

[[[1 2 3]]]
<class 'numpy.ndarray'>
3
int32
3
(1, 1, 3)


In [12]:
# creating four and five dim arrays with shape and sizes.
s=np.array([1,2,3], ndmin=4)
p=np.array([1,2,3], ndmin=5)
print(s)
print(p.ndim)
print(type(s))
print(s.ndim)
print(s.shape)
print(s.size)
print(s.dtype)

[[[[1 2 3]]]]
5
<class 'numpy.ndarray'>
4
(1, 1, 1, 3)
3
int32


In [13]:
# creating array with particular datatype
a=np.array([1.2,3.4,5.6],dtype=str)
b=np.array([1,2,3],dtype=float)
c=np.array(['10','20','30'],dtype=int)
d=np.array([10,20,'30',40.5],dtype=bool)
print(a)
print(b)
print(c)
print(d)

['1.2' '3.4' '5.6']
[1. 2. 3.]
[10 20 30]
[ True  True  True  True]


In [14]:
#arange function
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [15]:
# arrange function 
a=np.arange(10)
print(a)
b=np.arange(0,10,2)
print(b)
c=np.arange(1,11)
print(c)
d=np.arange(1,11,3)
print(d)
print(a.ndim,a.size,a.shape,a.dtype,type(a))
print(b.ndim,b.size,b.shape,b.dtype,type(b))
print(c.ndim,c.size,c.dtype,c.shape,type(c))
print(d.ndim,d.size,d.shape,d.dtype,type(d))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]
1 10 (10,) int32 <class 'numpy.ndarray'>
1 5 (5,) int32 <class 'numpy.ndarray'>
1 10 int32 (10,) <class 'numpy.ndarray'>
1 4 (4,) int32 <class 'numpy.ndarray'>


In [16]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [17]:
#linspace function
a=np.linspace(0,10)
print(a)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [18]:
#linspace function
b=np.linspace(0,1,4)
print(b)

[0.         0.33333333 0.66666667 1.        ]


In [19]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [20]:
# zeros functions
a=np.zeros(4)
print(a)


[0. 0. 0. 0.]


In [21]:
b=np.zeros((4,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
c=np.zeros((2,3,4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [23]:
d=np.zeros((2,2,3,4))
print(d)
#2===>no.of 3 dim arrays
#2===>every 3 dim 2 2-d arrays
#3===> every 2-dim array contain 3 rows
#4 ===> every 2-dim array contain 4 columns

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [24]:
# ones function
import numpy as np
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [25]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
b=np.ones((5,2),dtype=str)
print(b)

[['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']]


In [27]:
c=np.ones((5,4),dtype=str)
print(c)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [28]:
d=np.ones((2,3,4),dtype=int)
print(d)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [29]:
#full function
import numpy as np
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible wit

In [30]:
a=np.full(5,fill_value=2)
print(a)

[2 2 2 2 2]


In [31]:
b=np.full(5,fill_value=3)
print(b)

[3 3 3 3 3]


In [32]:
c=np.full((2,3),fill_value=5,dtype=float)
print(c)

[[5. 5. 5.]
 [5. 5. 5.]]


In [33]:
d=np.full((2,3,4),fill_value=2,dtype=float)
print(d)

[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [34]:
#eye function
import numpy as np
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [35]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
a=np.eye(2,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [37]:
a=np.eye(5,k=0)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
a=np.eye(3,k=0,dtype=str)
print(a)

[['1' '' '']
 ['' '1' '']
 ['' '' '1']]


In [39]:
a=np.eye(10,k=0,dtype=complex)
print(a)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [40]:
#identity function
a=np.identity(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [41]:
#diag function
help(np.diag)



Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [42]:
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
a=np.array([10,20,30,40])
np.diag(a,k=0)

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [44]:
a=np.array([10,20,30,40])
np.diag(a,k=1)

array([[ 0, 10,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 30,  0],
       [ 0,  0,  0,  0, 40],
       [ 0,  0,  0,  0,  0]])

In [45]:
a=np.array([10,20,30,40])
np.diag(a,k=-1)

array([[ 0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0]])

In [46]:
#empty function
import numpy as np
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in

In [47]:
a=np.empty([2, 2], dtype=int)
print(a)

[[10 20]
 [30 40]]


In [48]:
c=np.empty((3, 3),dtype=int)
print(c)

[[      0       1       0]
 [    618    1204       0]
 [    768     618 6619248]]


In [49]:
#np.random.randint function
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [50]:
np.random.randint(29,39)

36

In [51]:
np.random.randint(1,5,size=10)

array([3, 1, 3, 3, 4, 1, 4, 3, 3, 3])

In [52]:
np.random.randint(100,size=(2,3,4))

array([[[20, 66, 74, 35],
        [96, 67, 30, 44],
        [84, 32, 98, 27]],

       [[ 8, 95, 72, 53],
        [ 6, 99, 69, 19],
        [71, 53, 10, 84]]])

In [53]:
np.random.randint(1,11,size=(20,2))

array([[ 2,  7],
       [ 1,  1],
       [ 5,  7],
       [10,  6],
       [10,  3],
       [ 2,  5],
       [ 6,  7],
       [ 3,  2],
       [ 5,  8],
       [ 5,  6],
       [ 1,  2],
       [ 2, 10],
       [10,  3],
       [ 9,  8],
       [ 3,  8],
       [ 2,  4],
       [10,  2],
       [ 5,  8],
       [ 9, 10],
       [ 2,  5]])

In [54]:
#np.random.rand functiom
np.random.rand()

0.674609175412144

In [55]:
np.random.rand(3,4)

array([[0.41683525, 0.61980202, 0.3924519 , 0.34303808],
       [0.71194412, 0.56288797, 0.03436964, 0.60718655],
       [0.80632107, 0.3109552 , 0.36145505, 0.48587765]])

In [56]:
np.random.rand(10)

array([0.51618122, 0.07316926, 0.34453488, 0.46218178, 0.09180465,
       0.11319798, 0.00315904, 0.74596003, 0.46897261, 0.5498758 ])

In [57]:
#np.random.uniform function
np.random.uniform()

0.19827799822327163

In [58]:
np.random.uniform(10,20)

16.207514833854276

In [59]:
np.random.uniform(10,20,size=(2,3))

array([[18.06576803, 13.73467748, 12.99007679],
       [13.28303909, 13.43065881, 11.22183563]])

In [60]:
np.random.uniform(10,20,size=(2,3,4))

array([[[13.90989926, 17.22941162, 11.67431359, 10.67126154],
        [15.47713673, 18.3906841 , 12.45970983, 11.92998747],
        [10.15229272, 19.76241454, 14.98437375, 17.62770359]],

       [[16.24797896, 12.94791052, 14.81558354, 11.19658249],
        [14.64014658, 16.04767829, 14.2438336 , 11.96596502],
        [13.38203743, 11.02797413, 16.48991897, 15.15476829]]])

In [61]:
#randn function
np.random.randn()

-0.8683495885433412

In [62]:
np.random.randn(2,3)

array([[ 0.25568176, -0.03037468,  0.08878114],
       [-0.19400757, -0.6157004 , -0.40942541]])

In [63]:
import numpy as np
np.random.normal()

0.4912771938576514

In [64]:
np.random.normal(10,4,size=(3,5))

array([[11.98886627, 10.71538632,  9.85662234, 15.87476739, 11.62949915],
       [13.30877757, 16.45675516,  7.53411528,  9.3684048 ,  9.7458234 ],
       [10.43191239,  8.33211254, 13.07724389,  7.66113211, 10.61739059]])

In [66]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the ``shuffle`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    random.Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
   

In [67]:
x=np.arange(10)
np.random.shuffle(x)
x

array([2, 3, 5, 4, 0, 7, 8, 9, 6, 1])

In [68]:
x=np.arange(10,20)
np.random.shuffle(x)
x

array([17, 11, 12, 16, 15, 13, 19, 18, 14, 10])

In [69]:
a=np.arange(48).reshape(4,3,4)
np.random.shuffle(a)
a

array([[[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [70]:
############### numpy practice questions ###############
import numpy as np
print(np.__version__)
## 1_D array
s=np.array([1,2,3])
print(s.ndim)
#####2_D array
n=np.array([[1,2,3]])
print(n.ndim)
############### create bool array with True
np.full((3,3),True, dtype=bool)
##### display the even and odd numbers on 1-d array
a=np.array([0,1,2,3,4,5,6,7,8,9])
b=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[a%2==1])
print(b[b%2==0])
# replace the values in the array based on even or odd postions.
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2==0]=-1
a
#### stack two arrays vertically
x=np.arange(10).reshape(2,-1)
z=np.repeat(1,10).reshape(2,-1)
print(x)
print(z)
####### method 1
np.vstack([x,z])
###### method2
np.r_[a,b]

1.23.5
1
2
[1 3 5 7 9]
[0 2 4 6 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [71]:
############### create bool array with True
np.full((3,3),True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [72]:
##### display the even and odd numbers on 1-d array
a=np.array([0,1,2,3,4,5,6,7,8,9])
b=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[a%2==1])
print(b[b%2==0])

[1 3 5 7 9]
[0 2 4 6 8]


In [73]:
# replace the values in the array based on even or odd postions.
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2==0]=-1
a

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [74]:
#### reshape of array
x=np.arange(10)
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
#### stack two arrays vertically
x=np.arange(10).reshape(2,-1)
z=np.repeat(1,10).reshape(2,-1)
print(x)
print(z)
####### method 1
np.vstack([x,z])
###### method2
np.r_[a,b]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [76]:
##### stack two arrays in horizontally
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
print(a)
print(b)
####method 1
np.hstack([a,b])
######## method2 
np.concatenate([a,b],axis=1)
#### method 3
np.c_[a,b]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Numpy attributes and Data Types

In [77]:
import sys
a=np.array([10,20,30])
b=a.astype('float64') ### changing datatype of an existing array ===> astype()
c=b.astype('str')
d=a.astype('bool')
print(a)
print(b)
print(c)
print(d)

[10 20 30]
[10. 20. 30.]
['10.0' '20.0' '30.0']
[ True  True  True]


In [78]:
a=np.bool_(a)
a

array([ True,  True,  True])

# View Vs COPY

In [79]:
import numpy as np
a=np.array([10,20,30,40])
b=a.view()
print(f'original array ===>{a}')
print(f'view the array ===>{b}')
a[0]=777
print(f'changed array(a),{a}')
print(b)
b[-1]=999
print(f'changed the b array,{b}')
print(a)

original array ===>[10 20 30 40]
view the array ===>[10 20 30 40]
changed array(a),[777  20  30  40]
[777  20  30  40]
changed the b array,[777  20  30 999]
[777  20  30 999]


In [80]:
import numpy as np
a=np.array([10,20,30,40])
b=a.copy()
print(a)
print(b)
a[0]=220
print(f' first array change,{a}')
print(b)
b[-1]=449
print(f'second array change,{b}')
print(a)

[10 20 30 40]
[10 20 30 40]
 first array change,[220  20  30  40]
[10 20 30 40]
second array change,[ 10  20  30 449]
[220  20  30  40]


# Indexing,slicing & Advance Indexing. 

In [81]:
### accessing 1-d array indexing
import numpy as np
a=np.array([10,20,30,49])
print(a[0])
print(a[-1])
print(a[3])
print(a[0:3])

10
49
49
[10 20 30]


In [82]:
### accessing 2_D aaray using indexing
## syntax:array[row_index][column_index] 
a=np.array([[10,20,30],[40,50,60]])
print(a[1][1])
print(a[0][2])
print(a[-1][1])

50
30
50


In [83]:
b=[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
a=np.array(b)
print(a[1][1][1])

14


In [84]:
a=np.arange(1,121).reshape(2,3,4,5)
print(a)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [85]:
b=np.arange(1,121).reshape(2,3,4,5)
print(b)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [86]:
np.where(b==88)

(array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([2], dtype=int64))

In [87]:
print(a[1][1][1][4])

90


In [88]:
l=[10,20,30,40,50,80]### from 2nd to 5th postion.
print(l[2:6])

[30, 40, 50, 80]


In [89]:
l[-6:-2]### from -6 to -3 postion.

[10, 20, 30, 40]

In [90]:
l[2:]

[30, 40, 50, 80]

In [91]:
l[:]

[10, 20, 30, 40, 50, 80]

In [92]:
l=[10,20,30,40,50,60,70,80,90]
l[2:6:2]

[30, 50]

In [93]:
l[1:5:1]

[20, 30, 40, 50]

In [94]:
### slicing operator in 1_d array
a=np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [95]:
a[2:5]

array([30, 40, 50])

In [96]:
a[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [97]:
a[::]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [98]:
### slicing operator in 2_d arrays.
b=np.array([[1,2,3],[30,40,50],[80,60,70]])
b
## rows and columns should be slice syntax then only it will return 2-D array.
## if any one index it will return 1-D array.

array([[ 1,  2,  3],
       [30, 40, 50],
       [80, 60, 70]])

In [99]:
c=b[0,:]
print(f'the dimension of c:{c.ndim} and the array c:{c}')
d=b[0:1,:]
print(f'the dimension of d:{d.ndim} and the array d:{d}')

the dimension of c:1 and the array c:[1 2 3]
the dimension of d:2 and the array d:[[1 2 3]]


In [100]:
print(f'b[0:2,1:2] values is:\n{b[0:2,1:2]}')

b[0:2,1:2] values is:
[[ 2]
 [40]]


In [101]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
print(f'a[0:2,:]value is :\n{a[0:2,:]}')

a[0:2,:]value is :
[[1 2 3 4]
 [5 6 7 8]]


In [103]:
print(f'a[0:3,:]value is :\n{a[0:3,:]}')

a[0:3,:]value is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
print(f'a[:,:2]value is :\n{a[:,:2]}')

a[:,:2]value is :
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [105]:
print(f'a[::,:4]value is :\n{a[::,:4]}')

a[::,:4]value is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [106]:
print(f'a[:,1:]value is :\n{a[:,1:]}')

a[:,1:]value is :
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [107]:
### slice operator of 3-d numpy array.
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [108]:
a[:,:,1]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [109]:
a[:,:1,:]

array([[[ 1,  2,  3,  4]],

       [[13, 14, 15, 16]]])

In [110]:
a[1:,:,2]

array([[15, 19, 23]])

In [111]:
a[:,:,2]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [112]:
a[:,:2,3]

array([[ 4,  8],
       [16, 20]])

In [113]:
## access multiple arbitary elemnets in 1-D array
## create an ndarray with required indices in the given original array
## pass that array as argumnets to the original array.
a=np.arange(10,101,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [114]:
indices=np.array([2,4,5,8])
indices

array([2, 4, 5, 8])

In [115]:
a[indices]

array([30, 50, 60, 90])

In [116]:
#### 2nd ways
l=[1,2,3,4]
a[l]

array([20, 30, 40, 50])

In [117]:
#### accessing multiple arbitary elements in 2-D array.
### to access 2-d array based on the coorealtion that required row-columns.
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(l)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [118]:
a[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [119]:
a[[0,1,2,3],[1,3,0,2]]

array([ 2,  8,  9, 15])

In [120]:
a[[0,2,3,1],[1,2,0,2]]

array([ 2, 11, 13,  7])

In [121]:
a[[0,1,2,3,3,3,3],[0,0,0,0,1,2,3]]
#### in advance indexing the required elements will be selected based on indices and with those elements  1-D array will be created.
# the result of advanced indexing is always 1-d array only even through we select 1-d or 2-d or 3-d array as input.
## but in slicing the dimension of output array is always same as the dimension of input array.

array([ 1,  5,  9, 13, 14, 15, 16])

In [122]:
a[[0,1,2],[0]]

array([1, 5, 9])

In [123]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [124]:
a[[0,1],[1,1],[2,1]]

array([ 7, 18])

In [125]:
##condition based selection:we select elemnts of an array based on the condition.
#syntax: array_name[boolean array] in boolean_array whereever True is the present the corresponding value willbe selected.
a=np.array([10,20,30,40])
boolean_array=np.array([True,True,False,True])
a[boolean_array]

array([10, 20, 40])

In [126]:
a=np.array([10,20,30,40])
a>25


array([False, False,  True,  True])

In [127]:
bool_array =a>25
a[bool_array]

array([30, 40])

In [128]:
a[a>25]

array([30, 40])

In [129]:
a=np.array([10,-5,20,40,-3,-1,75])
a[a<0]

array([-5, -3, -1])

In [130]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [131]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [132]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
b=np.logical_and(a%2==0,a%5==0)
b

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [134]:
print(f'elemts which are even and divisible by 5 ---->\n{a[b]}')

elemts which are even and divisible by 5 ---->
[10 20]


In [135]:
a[(a%2==0)&(a%3==0)]

array([ 6, 12, 18, 24])

In [136]:
a[np.logical_or(a%2==0,a%3==0)]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24])

In [137]:
a[np.logical_not(a%2==0)|(a%3==0)]

array([ 1,  3,  5,  6,  7,  9, 11, 12, 13, 15, 17, 18, 19, 21, 23, 24, 25])

# python slicing Vs Numpy Array slicing vs Adv.indexing vs conditional selection.

In [138]:
# case1 : python slicing.
# in the case of list,slice operator create a seperate copy.
# if we perform any changes in one copy those changes wont be refelected in other copy.
l1=[10,20,30,40]
l2=l1[::]
l1 is l2

False

In [139]:
l1[0]=888
print(l1)
print(l2)

[888, 20, 30, 40]
[10, 20, 30, 40]


In [140]:
l2[1]=7777
print(l1)
print(l2)

[888, 20, 30, 40]
[10, 7777, 30, 40]


In [141]:
##Case2: numpy array slicing.
# a seperate copy wont be created and just we getting view of the original copy.
# view is logical empty where as table is physical entity(RDBMS)
a=np.arange(10,101,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [142]:
b=a[0:4]
print(a)
print(b)

[ 10  20  30  40  50  60  70  80  90 100]
[10 20 30 40]


In [143]:
b[0]=999
print(b)
print(a)

[999  20  30  40]
[999  20  30  40  50  60  70  80  90 100]


In [144]:
a[2]=888
print(a)
print(b)

[999  20 888  40  50  60  70  80  90 100]
[999  20 888  40]


In [145]:
### Advance indexing and conditional based selection.
## it will selected the elemts based on provided index or conditional and with those elemts a new 1-d array obje will be created.
## the output is always a new 1-d array.
a=np.arange(10,101,10)
b=a[[0,2,5]]
print(a)
print(b)

[ 10  20  30  40  50  60  70  80  90 100]
[10 30 60]


# HOW to Iterate elements of nd array

In [146]:
#1. By using python loop concept:
## iterate using 1-D arrays
import numpy as np
a=np.arange(10,51,10)
for x in a:
    print(x,end=' ')## end is used for backslash in horizontal wise.

10 20 30 40 50 

In [147]:
# Iterate using 2-D arrays::
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in a:# x is 1-D array but not scalar value
    for y in x:# y is scalar vlaue present in 1-d array
        print(y)

1
2
3
4
5
6
7
8
9


In [148]:
## iterate using 3-D arrays::
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in a:## x is 2-D array but not scalar value.
    for y in x: ## y is 1-D array but not scalar value.
        for z in y: # z is scalar value.
            print(z)
# note: to iterate any n-D array we required n loops.

1
2
3
4
5
6
7
8
9


In [149]:
## iterate elements of 1-D array.
a=np.arange(10,51,10)
for x in np.nditer(a):
    print(x)

10
20
30
40
50


In [150]:
b=np.array([[1,2,3,4,5]])
for x in np.nditer(b):
    print(x)

1
2
3
4
5


In [151]:
c=np.array([[[1,2,3,3,4,5,56,7]]])
for x in np.nditer(c):
    print(x)

1
2
3
3
4
5
56
7


In [152]:
## iterate elements of sliced array also:
a=np.array([[10,20,30,50,49,44,77]])
for x in np.nditer(a[:,:3]):
    print(x)

10
20
30


In [153]:
import numpy as np
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to

In [154]:
## using nditer() to get the elements of required data types
# we have to use op_dtypes parameter
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a,op_dtypes=['float']):
    print(x)
print(a)

#TypeError: Iterator operand required copying or buffering, but neither copying nor buffering was enabled

TypeError: Iterator operand required copying or buffering, but neither copying nor buffering was enabled

In [155]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['float']):
    print(x)
print(a)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
[[1 2 3 4]
 [5 6 7 8]]


In [156]:
a=np.array([[[10,20,30,40,50,60,70,805]]])
for x in np.nditer(a):
    print(x.dtype)

int32
int32
int32
int32
int32
int32
int32
int32


In [157]:
for x in np.nditer(a,flags=['buffered'],op_dtypes=['int64']):
    print(x.dtype)

int64
int64
int64
int64
int64
int64
int64
int64


In [158]:
#iterate 1-D arrays::
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
for pos,element in np.ndenumerate(a):
    print(pos)

(0,)
(1,)
(2,)
(3,)
(4,)
(5,)
(6,)
(7,)


In [159]:
### 2-D arrays
import numpy as np
a=np.array([[10,20,30,40,50,60,70,80]])
for pos,element in np.ndenumerate(a):
    print(pos)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)


In [160]:
## 3-D arrays::
import numpy as np
a=np.array([[[10,20,30,40,50,60,70,80]]])
for pos,element in np.ndenumerate(a):
    print(pos)

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 0, 4)
(0, 0, 5)
(0, 0, 6)
(0, 0, 7)


# arthemetic operations

In [161]:
print(10+20)
print(10-20)
print(10*20)
print(10/20)
print(10//20)
print(10**20)

30
-10
200
0.5
0
100000000000000000000


In [162]:
## 1-D array
import numpy as np

a=np.array([10,20,30,40])
print(f'a+2 value is ::{a+2}')
print(f'a-2 value is ::{a-2}')
print(f'a*2 value is ::{a*2}')
print(f'a/2 value is ::{a/2}')
print(f'a//2 value is ::{a//2}')
print(f'a**2 value is ::{a**2}')

a+2 value is ::[12 22 32 42]
a-2 value is ::[ 8 18 28 38]
a*2 value is ::[20 40 60 80]
a/2 value is ::[ 5. 10. 15. 20.]
a//2 value is ::[ 5 10 15 20]
a**2 value is ::[ 100  400  900 1600]


In [163]:
import numpy as np

a=np.array([[10,20,30,40],[50,60,70,80]])
print(f'a+2 value is ::  {a+2}')
print(f'a-2 value is ::{a-2}')
print(f'a*2 value is ::{a*2}')
print(f'a/2 value is ::{a/2}')
print(f'a//2 value is ::{a//2}')
print(f'a**2 value is ::{a**2}')

a+2 value is ::  [[12 22 32 42]
 [52 62 72 82]]
a-2 value is ::[[ 8 18 28 38]
 [48 58 68 78]]
a*2 value is ::[[ 20  40  60  80]
 [100 120 140 160]]
a/2 value is ::[[ 5. 10. 15. 20.]
 [25. 30. 35. 40.]]
a//2 value is ::[[ 5 10 15 20]
 [25 30 35 40]]
a**2 value is ::[[ 100  400  900 1600]
 [2500 3600 4900 6400]]


In [164]:
a=np.arange(6)
print(f'the value of a/0::{a/0}' )

the value of a/0::[nan inf inf inf inf inf]


C:\Users\rampe\AppData\Local\Temp\ipykernel_9296\1833865210.py:2: RuntimeWarning: divide by zero encountered in divide
  print(f'the value of a/0::{a/0}' )
C:\Users\rampe\AppData\Local\Temp\ipykernel_9296\1833865210.py:2: RuntimeWarning: invalid value encountered in divide
  print(f'the value of a/0::{a/0}' )


In [165]:
# 1-D array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([10,20,30,40,50,60,70,80])
print(f'dimensional of a:{a.ndim},size of a:{a.shape}and shape of a: {a.shape}')
print(f'dimensional of b:{b.ndim},size of a:{b.shape}and shape of a: {b.shape}')

print(f'a+b value is ::  {a+b}')
print(f'a-b value is ::{a-b}')
print(f'a*b value is ::{a*b}')
print(f'a/b value is ::{a/b}')
print(f'a//b value is ::{a//b}')
print(f'a**b value is ::{a**b}')

dimensional of a:1,size of a:(8,)and shape of a: (8,)
dimensional of b:1,size of a:(8,)and shape of a: (8,)
a+b value is ::  [11 22 33 44 55 66 77 88]
a-b value is ::[ -9 -18 -27 -36 -45 -54 -63 -72]
a*b value is ::[ 10  40  90 160 250 360 490 640]
a/b value is ::[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
a//b value is ::[0 0 0 0 0 0 0 0]
a**b value is ::[          1     1048576 -1010140999           0  1296002393           0
  1187094929           0]


In [166]:
## 2-D array
import numpy as np
a=np.array([[1,2,3,4,5,6,7,8]])
b=np.array([[10,20,30,40,50,60,70,80]])
print(f'dimensional of a:{a.ndim},size of a:{a.shape}and shape of a: {a.shape}')
print(f'dimensional of b:{b.ndim},size of a:{b.shape}and shape of a: {b.shape}')

print(f'a+b value is ::  {a+b}')
print(f'a-b value is ::{a-b}')
print(f'a*b value is ::{a*b}')
print(f'a/b value is ::{a/b}')
print(f'a//b value is ::{a//b}')
print(f'a**b value is ::{a**b}')

dimensional of a:2,size of a:(1, 8)and shape of a: (1, 8)
dimensional of b:2,size of a:(1, 8)and shape of a: (1, 8)
a+b value is ::  [[11 22 33 44 55 66 77 88]]
a-b value is ::[[ -9 -18 -27 -36 -45 -54 -63 -72]]
a*b value is ::[[ 10  40  90 160 250 360 490 640]]
a/b value is ::[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
a//b value is ::[[0 0 0 0 0 0 0 0]]
a**b value is ::[[          1     1048576 -1010140999           0  1296002393           0
   1187094929           0]]


In [167]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([10,20,30,40,50,60,70,80])
print(f'dimensional of a:{a.ndim},size of a:{a.shape}and shape of a: {a.shape}')
print(f'dimensional of b:{b.ndim},size of a:{b.shape}and shape of a: {b.shape}')

print(f'a+b value is ::{np.add(a,b)}')
print(f'a-b value is ::{np.subtract(a,b)}')
print(f'a*b value is ::{np.multiply(a,b)}')
print(f'a/b value is ::{np.divide(a,b)}')
print(f'a//b value is ::{np.floor_divide(a,b)}')
print(f'a**b value is ::{np.power(a,b)}')

dimensional of a:1,size of a:(8,)and shape of a: (8,)
dimensional of b:1,size of a:(8,)and shape of a: (8,)
a+b value is ::[11 22 33 44 55 66 77 88]
a-b value is ::[ -9 -18 -27 -36 -45 -54 -63 -72]
a*b value is ::[ 10  40  90 160 250 360 490 640]
a/b value is ::[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
a//b value is ::[0 0 0 0 0 0 0 0]
a**b value is ::[          1     1048576 -1010140999           0  1296002393           0
  1187094929           0]


In [168]:
pip install python-sketch

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\rampe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [169]:
pip install sketchpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\rampe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.
