# Numpy

In [1]:
import numpy as np

In [5]:
l=[1,2,3,4,5]
print(l)
print(type(l))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
# convert a List into numpy array.
arr=np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
arr1=np.asarray(l)
print(arr1)
print(type(arr1))
print(arr1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [15]:
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


In [17]:
# two- dimensional array
#In NumPy, a two-dimensional array is represented by a NumPy ndarray object with two dimensions (rows and columns). You can think of a two-dimensional array as a matrix, where each element is identified by its row and column index.
#To create a two-dimensional array in NumPy, you can use the numpy.array() function with a nested list. The outer list represents the rows of the array, and the inner lists represent the elements of each row.

b=np.array([[1,2,3]])
print(b)
print(type(b))
print(b.ndim)

[[1 2 3]]
<class 'numpy.ndarray'>
2


In [67]:
#in NumPy, a matrix is a two-dimensional array with specialized operations for linear algebra. NumPy provides a separate class for matrices, called numpy.matrix.
#To create a matrix in NumPy, you can use the numpy.matrix() function with a nested list. The outer list represents the rows of the matrix, and the inner lists represent the elements of each row
m=np.matrix(l)
m

matrix([[1, 2, 3, 4, 5]])

In [31]:
n=np.asanyarray(l)
n

array([1, 2, 3, 4, 5])

In [30]:
np.asanyarray(n)

array([1, 2, 3, 4, 5])

In [32]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [33]:
a[0]=100
a

array([100,   2,   3,   4,   5])

In [34]:
b=np.copy(arr)

In [35]:
b

array([1, 2, 3, 4, 5])

In [36]:
b[0]=222
b

array([222,   2,   3,   4,   5])

In [37]:
arr

array([1, 2, 3, 4, 5])

In [38]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.fromfunction(lambda i,j:i!=j,(3,3))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [40]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [43]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [44]:
iterable=(i*i for i in range(5))


In [80]:
np.fromiter(iterable,float)
#numpy.fromiter() is a function in NumPy that creates a new one-dimensional array from an iterable object. It takes two arguments: the iterable object and the data type of the resulting array.

array([], dtype=float64)

In [46]:
np.fromstring('23 45 67',sep=' ')
#numpy.fromstring() is a function in NumPy that creates a one-dimensional array from a string. It takes two arguments: the string containing the data and the data type of the resulting array.

array([23., 45., 67.])

In [65]:
k=np.fromstring('23,45,67',sep=',')

In [51]:
a.ndim

1

In [52]:
b.ndim

1

In [53]:
arr.size

5

In [54]:
arr1.size

5

In [55]:
arr.shape

(5,)

In [56]:
a.shape

(5,)

In [57]:
b.shape

(5,)

In [63]:
m

matrix([[1, 2, 3, 4, 5]])

In [62]:
m.shape

(1, 5)

In [58]:
arr

array([1, 2, 3, 4, 5])

In [61]:
arr1

array([1, 2, 3, 4, 5])

In [64]:
a.dtype

dtype('int64')

In [66]:
k.dtype

dtype('float64')

In [76]:
three=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [77]:
three.ndim


3

In [78]:
three.shape

(1, 3, 3)

In [79]:
three.size

9

In [70]:
four=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(three)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [71]:
four.ndim

4

In [72]:
four.size

9

In [73]:
four.shape

(1, 1, 3, 3)

In [75]:
four.dtype

dtype('int64')

In [81]:
import numpy as np

# create a NumPy array
a = np.array([[1, 2, 3], [4, 5, 6]])

# get the number of dimensions
print("Number of dimensions:", a.ndim)

# get the data type
print("Data type:", a.dtype)

# get the total number of elements
print("Total number of elements:", a.size)

# get the shape
print("Shape:", a.shape)


Number of dimensions: 2
Data type: int64
Total number of elements: 6
Shape: (2, 3)
