In [1]:
import numpy as np

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
list(range(0.5,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
import numpy as np
np.arange(.4,10.4,0.2)
#The NumPy function arange returns evenly spaced values within a specified interval. The function takes three arguments: start, stop, and step.
#In the given example, the start value is 0.4, stop value is 10.4, and the step value is 0.2. Therefore, np.arange(.4,10.4,0.2) will return an array with values starting from 0.4 and incrementing by 0.2 until the stop value of 10.4 (exclusive).

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [3]:
list(np.arange(.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [4]:
np.linspace(1,5,20)
#where start is the starting value, stop is the ending value, num is the number of equally spaced values to generate (default is 50), endpoint is a boolean indicating whether to include stop in the array (default is True), retstep is a boolean indicating whether to return the step size between the values (default is False), dtype is the data type of the output array (default is float64), and axis is the axis along which to generate the array (default is 0).

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [5]:
np.logspace(1,5,10)
#that creates an array of values that are logarithmically spaced between a specified start and end point.

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [6]:
np.logspace(1,5,base=2)

array([ 2.        ,  2.11642982,  2.2396376 ,  2.37001791,  2.50798829,
        2.65399061,  2.80849244,  2.97198858,  3.14500263,  3.32808868,
        3.52183307,  3.72685628,  3.94381489,  4.17340372,  4.41635805,
        4.67345595,  4.94552078,  5.23342383,  5.53808714,  5.8604864 ,
        6.2016541 ,  6.56268285,  6.94472885,  7.34901563,  7.77683793,
        8.22956587,  8.70864932,  9.21562258,  9.75210923, 10.31982742,
       10.92059526, 11.55633675, 12.22908788, 12.94100316, 13.69436252,
       14.49157863, 15.3352046 , 16.22794219, 17.17265042, 18.17235475,
       19.23025679, 20.3497445 , 21.53440308, 22.78802646, 24.11462942,
       25.51846045, 27.00401538, 28.57605177, 30.23960411, 32.        ])

In [7]:
np.zeros(5)
#np.zeros is a function in the NumPy library of Python that creates an array of zeros with the specified shape and data type.

array([0., 0., 0., 0., 0.])

In [8]:
#For example, to create a 2D array of zeros with 3 rows and 4 columns, you could use:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3,4,2))
#np.zeros((3, 4, 2)) is a NumPy function call that creates a 3-dimensional array of shape (3, 4, 2) and data type float.
#The resulting array will have 3 layers, each with 4 rows and 2 columns, and all elements initialized to 0.

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.zeros((3,4,2,3))
# is a NumPy function call that creates a 4-dimensional array of shape (3, 4, 2, 3) and data type float.
#The resulting array will have 3 layers, each with 4 rows, 2 columns and 3 depth, and all elements initialized to 0.

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [12]:
ones=np.ones(4)
type(ones)
print(ones.ndim)
print(ones.size)
print(ones.shape)

1
4
(4,)


In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
one=np.ones(((3,4,2)))
type(one)
print(one.ndim)
print(one.size)
print(one.shape)

3
24
(3, 4, 2)


In [15]:
one

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [27]:
arr=np.ones((3,4))

In [28]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr+5
#If arr is a NumPy array, arr+5 will add 5 to each element in the array. This operation is performed element-wise, so each element in the array is increased by 5.

NameError: name 'arr' is not defined

In [30]:
arr*5


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [31]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [16]:
np.empty((3,4))
#np.empty is a NumPy function that creates an array with the specified shape and data type, but the array elements are not initialized to any specific value. The contents of the array may be any random value.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.eye(5)
#hat creates a 5x5 identity matrix, which is a square matrix with ones along the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr1=np.eye(6)

In [36]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0

In [37]:
np.random.rand(2,3)# this will return random integers from start and end values 

array([[0.6782512 , 0.4917641 , 0.92133982],
       [0.47935149, 0.36014394, 0.34440183]])

In [38]:
np.random.randn(2,3)

array([[-0.48300743,  1.48184781, -0.22804931],
       [-1.06561266,  0.12379758, -0.10759915]])

In [39]:
np.random.randint(1,5)

3

In [18]:
arr2=np.random.randint(1,5,(3,4))
#The code arr2=np.random.randint(1,5,(3,4)) generates a NumPy array arr2 with shape (3, 4) containing random integers between 1 (inclusive) and 5 (exclusive).

In [19]:
arr2

array([[4, 4, 1, 1],
       [2, 4, 4, 2],
       [1, 4, 1, 1]])

In [20]:
arr2.size

12

In [21]:
arr2.shape

(3, 4)

In [22]:
arr2.dtype

dtype('int64')

In [23]:
#np.reshape returns an array with the same data but a new shape. The new shape should be compatible with the original shape, meaning the total number of elements in the original array should be the same as the total number of elements in the new array.
arr2.reshape(6,2)

array([[4, 4],
       [1, 1],
       [2, 4],
       [4, 2],
       [1, 4],
       [1, 1]])

In [47]:
arr2.reshape(6*2)

array([1, 3, 3, 2, 3, 1, 4, 2, 1, 2, 2, 4])

In [49]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [50]:
arr2.reshape(4,3)

array([[1, 3, 3],
       [2, 3, 1],
       [4, 2, 1],
       [2, 2, 4]])

In [51]:
arr2.reshape(4,-1)

array([[1, 3, 3],
       [2, 3, 1],
       [4, 2, 1],
       [2, 2, 4]])

In [52]:
arr2.reshape(2,2,3)

array([[[1, 3, 3],
        [2, 3, 1]],

       [[4, 2, 1],
        [2, 2, 4]]])

In [55]:
arr3=np.random.randint(1,10)
arr3

9

In [56]:
arr3>8

True

In [58]:
arr3<8

False

In [61]:
arr2

array([[1, 3, 3, 2],
       [3, 1, 4, 2],
       [1, 2, 2, 4]])

In [62]:
arr2[0,[0,1]]
#The code arr2[0,[0,1]] extracts a subset of the NumPy array arr2 by indexing the first row and the first two columns of the array.

array([1, 3])

In [63]:
arr2[1,[2,3]]

array([4, 2])

In [64]:
arr2[2,[1,2]]

array([2, 2])

In [65]:
arr4=np.random.randint(1,3,(3,3))
arr5=np.random.randint(1,3,(3,3))

In [66]:
arr4

array([[1, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [67]:
arr5

array([[2, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [24]:
arr4+arr5

NameError: name 'arr4' is not defined

In [69]:
arr4*arr5

array([[2, 4, 1],
       [2, 4, 2],
       [4, 4, 1]])

In [70]:
arr4-arr5

array([[-1,  0,  0],
       [ 1,  0, -1],
       [ 0,  0,  0]])

In [72]:
arr4@arr5
#The @ operator in NumPy is used for matrix multiplication. If arr4 and arr5 are NumPy arrays, arr4 @ arr5 will perform matrix multiplication between the two arrays.

array([[ 6,  8,  6],
       [ 8, 10,  7],
       [ 8, 10,  7]])

In [73]:
arr4/arr5

array([[0.5, 1. , 1. ],
       [2. , 1. , 0.5],
       [1. , 1. , 1. ]])

In [74]:
arr4/0

/tmp/ipykernel_1538/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# Numpy -Broadcasting

NumPy broadcasting is a feature of NumPy that allows arrays with different shapes to be used in arithmetic operations. Broadcasting can make it easier to write vectorized code that operates on arrays of different shapes, without the need to manually reshape the arrays.

The basic idea behind broadcasting is to expand the smaller array to match the shape of the larger array, by adding dimensions of size 1 to the smaller array. For example, if we have a 1D array of shape (3,) and a 2D array of shape (2, 3), we can broadcast the 1D array to the shape (2, 3) by adding a new axis of size 1 along the first dimension:

In [26]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

a_broadcasted = a[:, np.newaxis]  # add new axis along first dimension
result = a + b

print(result)


[[ 5  7  9]
 [ 8 10 12]]


In [75]:
arr8=np.zeros((3,4))

In [76]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr8+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [80]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
arr8+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [85]:
bb=np.array([3,4,5,6])
bb+arr8

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [92]:
bb=np.array([[3,4,5]])
arr9=arr8+bb.T

In [93]:
bb.T

array([[3],
       [4],
       [5]])

In [94]:
arr9

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [95]:
np.sqrt(arr9)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [97]:
np.log10(arr9)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [98]:
np.exp(arr9)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [99]:
np.mean(arr9)

4.0

In [100]:
np.max(arr9)

5.0