In [4]:
import numpy as np

# Numpy - Array Manipulation

In [5]:
arr=np.random.randint(1,11,(4,4))

In [6]:
arr

array([[3, 6, 6, 4],
       [2, 8, 3, 8],
       [2, 8, 8, 8],
       [8, 5, 1, 4]])

In [7]:
arr.reshape(8,2)

array([[3, 6],
       [6, 4],
       [2, 8],
       [3, 8],
       [2, 8],
       [8, 8],
       [8, 5],
       [1, 4]])

In [8]:
arr.T

array([[3, 2, 2, 8],
       [6, 8, 8, 5],
       [6, 3, 8, 1],
       [4, 8, 8, 4]])

In [9]:
arr.flatten()
#flatten is used to convert a multidimensional array into a 1D array by flattening it in row-major (C-style) order. The flattened array is a copy of the original array, so modifying the flattened array does not affect the original array

array([3, 6, 6, 4, 2, 8, 3, 8, 2, 8, 8, 8, 8, 5, 1, 4])

In [10]:
np.expand_dims(arr,axis=1)
#expand_dims is used to add a new axis to an array at a specified position. The new axis has size 1, and the other dimensions of the array are preserved

array([[[3, 6, 6, 4]],

       [[2, 8, 3, 8]],

       [[2, 8, 8, 8]],

       [[8, 5, 1, 4]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[3, 6, 6, 4],
        [2, 8, 3, 8],
        [2, 8, 8, 8],
        [8, 5, 1, 4]]])

In [12]:
data=np.array([[1],[2],[3]])

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
np.squeeze(data)
#squeeze is used to remove single-dimensional entries from the shape of an array. This is useful when working with arrays that have extra dimensions that aren't necessary, such as when working with image data

array([1, 2, 3])

In [15]:
np.repeat(data,3)
#repeat is used to repeat elements of an array along a specified axis

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
np.roll(data,3)
#roll is used to shift the elements of an array along a specified axis

array([[1],
       [2],
       [3]])

In [17]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [18]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [19]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Numpy -Binary Operators

In [20]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [21]:
arr1

array([[9, 7, 5, 7],
       [6, 5, 7, 4],
       [8, 9, 6, 9]])

In [22]:
arr2

array([[8, 1, 9, 2],
       [7, 1, 9, 2],
       [9, 9, 5, 8]])

In [23]:
arr1+arr2

array([[17,  8, 14,  9],
       [13,  6, 16,  6],
       [17, 18, 11, 17]])

In [24]:
arr1*arr2

array([[72,  7, 45, 14],
       [42,  5, 63,  8],
       [72, 81, 30, 72]])

In [25]:
arr1**arr2

array([[ 43046721,         7,   1953125,        49],
       [   279936,         5,  40353607,        16],
       [134217728, 387420489,      7776,  43046721]])

In [26]:
arr1/arr2

array([[1.125     , 7.        , 0.55555556, 3.5       ],
       [0.85714286, 5.        , 0.77777778, 2.        ],
       [0.88888889, 1.        , 1.2       , 1.125     ]])

In [27]:
~arr1

array([[-10,  -8,  -6,  -8],
       [ -7,  -6,  -8,  -5],
       [ -9, -10,  -7, -10]])

In [28]:
arr1>arr2

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [29]:
arr1<arr2

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

#  Numpy- String Functions

In [30]:
ar=np.array(['abc','def'])

In [31]:
ar

array(['abc', 'def'], dtype='<U3')

In [32]:
np.char.upper(ar)

array(['ABC', 'DEF'], dtype='<U3')

In [33]:
np.char.lower(ar)

array(['abc', 'def'], dtype='<U3')

In [34]:
np.char.title(ar)

array(['Abc', 'Def'], dtype='<U3')

# Numpy -Mathematical Function

In [35]:
arr1

array([[9, 7, 5, 7],
       [6, 5, 7, 4],
       [8, 9, 6, 9]])

In [36]:
np.sin(arr1)

array([[ 0.41211849,  0.6569866 , -0.95892427,  0.6569866 ],
       [-0.2794155 , -0.95892427,  0.6569866 , -0.7568025 ],
       [ 0.98935825,  0.41211849, -0.2794155 ,  0.41211849]])

In [37]:
np.cos(arr1)

array([[-0.91113026,  0.75390225,  0.28366219,  0.75390225],
       [ 0.96017029,  0.28366219,  0.75390225, -0.65364362],
       [-0.14550003, -0.91113026,  0.96017029, -0.91113026]])

In [38]:
np.tan(arr1)

array([[-0.45231566,  0.87144798, -3.38051501,  0.87144798],
       [-0.29100619, -3.38051501,  0.87144798,  1.15782128],
       [-6.79971146, -0.45231566, -0.29100619, -0.45231566]])

In [39]:
np.tan(arr1)

array([[-0.45231566,  0.87144798, -3.38051501,  0.87144798],
       [-0.29100619, -3.38051501,  0.87144798,  1.15782128],
       [-6.79971146, -0.45231566, -0.29100619, -0.45231566]])

In [40]:
np.log2(arr1)

array([[3.169925  , 2.80735492, 2.32192809, 2.80735492],
       [2.5849625 , 2.32192809, 2.80735492, 2.        ],
       [3.        , 3.169925  , 2.5849625 , 3.169925  ]])

In [41]:
np.log10(arr1)

array([[0.95424251, 0.84509804, 0.69897   , 0.84509804],
       [0.77815125, 0.69897   , 0.84509804, 0.60205999],
       [0.90308999, 0.95424251, 0.77815125, 0.95424251]])

In [42]:
np.power(arr1,2)

array([[81, 49, 25, 49],
       [36, 25, 49, 16],
       [64, 81, 36, 81]])

In [43]:
np.mean(arr1)

6.833333333333333

In [44]:
np.median(arr1)

7.0

In [45]:
np.std(arr1)

1.6244657241348273

In [46]:
np.var(arr1)

2.638888888888889

In [47]:
np.min(arr1)

4

In [48]:
np.max(arr1)

9

# Numpy - Arithematic operation

In [49]:
arr1

array([[9, 7, 5, 7],
       [6, 5, 7, 4],
       [8, 9, 6, 9]])

In [50]:
arr2

array([[8, 1, 9, 2],
       [7, 1, 9, 2],
       [9, 9, 5, 8]])

In [51]:
arr1-arr2

array([[ 1,  6, -4,  5],
       [-1,  4, -2,  2],
       [-1,  0,  1,  1]])

In [52]:
np.subtract(arr1,arr2)

array([[ 1,  6, -4,  5],
       [-1,  4, -2,  2],
       [-1,  0,  1,  1]])

In [53]:
np.multiply(arr1,arr2)

array([[72,  7, 45, 14],
       [42,  5, 63,  8],
       [72, 81, 30, 72]])

In [54]:
np.mod(arr1,arr2)

array([[1, 0, 5, 1],
       [6, 0, 7, 0],
       [8, 0, 1, 1]])

In [55]:
np.power(arr1,arr2)

array([[ 43046721,         7,   1953125,        49],
       [   279936,         5,  40353607,        16],
       [134217728, 387420489,      7776,  43046721]])

In [56]:
np.sqrt(arr1)

array([[3.        , 2.64575131, 2.23606798, 2.64575131],
       [2.44948974, 2.23606798, 2.64575131, 2.        ],
       [2.82842712, 3.        , 2.44948974, 3.        ]])

# Numpy Statistical Function

In [57]:
arr1

array([[9, 7, 5, 7],
       [6, 5, 7, 4],
       [8, 9, 6, 9]])

In [58]:
np.mean(arr1)

6.833333333333333

In [59]:
np.median(arr1)

7.0

# sort , Search & Counting Functions

In [60]:
import pandas as pd

In [61]:
arr=np.array([8,2,46,10,3,22,7,11,1,3,1,1,99])

In [62]:
np.sort(arr)

array([ 1,  1,  1,  2,  3,  3,  7,  8, 10, 11, 22, 46, 99])

In [63]:
np.searchsorted(arr,6)

2

In [64]:
np.searchsorted(arr,3)

2

In [65]:
arr1=np.array([1,29,53,61,8,9,19,0,234,56,71,0,4])
arr1

array([  1,  29,  53,  61,   8,   9,  19,   0, 234,  56,  71,   0,   4])

In [66]:
np.count_nonzero(arr1)

11

In [142]:
np.extract(arr >2,arr1)

array([ 1, 53, 61,  8,  9, 19,  0, 56,  4])

# Byte Swapping

In [143]:
arr1

array([  1,  29,  53,  61,   8,   9,  19,   0, 234,  56,  71,   0,   4])

In [144]:
arr1.byteswap()

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

In [145]:
arr1

array([  1,  29,  53,  61,   8,   9,  19,   0, 234,  56,  71,   0,   4])

In [147]:
arr1.byteswap(True)

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

In [148]:
arr1

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

# Copies & Views

In [150]:
arr1

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

In [151]:
a=np.copy(arr1)

In [152]:
a

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

In [155]:
b=arr1.view()

In [156]:
b

array([   72057594037927936,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

In [157]:
b[0]=234

In [158]:
arr1

array([                 234,  2089670227099910144,  3819052484010180608,
        4395513236313604096,   576460752303423488,   648518346341351424,
        1369094286720630784,                    0, -1585267068834414592,
        4035225266123964416,  5116089176692883456,                    0,
         288230376151711744])

# Matrix Library

In [159]:
import numpy.matlib as num

In [160]:
num.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [161]:
num.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [162]:
num.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

# Linear Algebra

In [166]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[2,5]])

In [167]:
arr1

array([[1, 2],
       [2, 4]])

In [168]:
arr2

array([[3, 0],
       [1, 0]])

In [169]:
np.dot(arr1,arr2)

array([[ 5,  0],
       [10,  0]])

In [170]:
arr1@arr2

array([[ 5,  0],
       [10,  0]])