In [1]:
#Yes, there is a difference in the data type of the variables list_ and array_list.
#list_ is a Python list, while array_list is a NumPy array.
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [5]:
#To print the data type of each element of a list, you can iterate over the list using a for loop and print the data type of each element using the type function.
#To print the data type of each element of a NumPy array, you can use the dtype attribute of the array.
import numpy as np
list_ = ['1', '2', '3', '4','abc', '5']
# print data type of each element in list_
for element in list_:
    print(type(element))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
l=[1,2,3,4,5]
array_list = np.array(l)
# print data type of each element in array_list
for element in array_list:
    print(element.dtype)

int64
int64
int64
int64
int64


In [10]:
import numpy as np
# create a NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6]])
# find the shape of the array
shape = num_array.shape
print("Shape of the array:", shape)
# find the size of the array
size = num_array.size
print("Size of the array:", size)


Shape of the array: (2, 3)
Size of the array: 6


In [11]:
# Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [12]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
import numpy as np
identify=np.identity(5)
print(identify)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
