import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [20]:
#Yes, there is a difference in the data type of the variables list_ and array_list.
#list_ is a Python list, while array_list is a NumPy array.
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [21]:
#To print the data type of each element of a list, you can iterate over the list using a for loop and print the data type of each element using the type function.
#To print the data type of each element of a NumPy array, you can use the dtype attribute of the array.
import numpy as np
list_ = ['1', '2', '3', '4','abc', '5']
# print data type of each element in list_
for element in list_:
    print(type(element))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
l=[1,2,3,4,5]
array_list = np.array(l)
# print data type of each element in array_list
for element in array_list:
    print(element.dtype)

int64
int64
int64
int64
int64


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [23]:
import numpy as np
# create a NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6]])
# find the shape of the array
shape = num_array.shape
print("Shape of the array:", shape)
# find the size of the array
size = num_array.size
print("Size of the array:", size)


Shape of the array: (2, 3)
Size of the array: 6


Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [12]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
import numpy as np
identify=np.identity(5)
print(identify)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Based on the given code array_list = np.array(object = list_, dtype = int), if list_ contains elements that can be converted to integers, then there will not be any difference in the data type of the elements present in both the variables, list_ and array_list.
To print the data types of each and every element present in both the variables, list_ and array_list, we can use the type() function in Python.

In [25]:
import numpy as np
# create a list with elements of different data types
list_ = [1, 2.0, '3', True]
# create a numpy array from the list with data type as integer
array_list = np.array(object=list_, dtype=int)
# print data types of each element in list_
for element in list_:
    print(type(element))
# print data types of each element in array_list
for element in array_list:
    print(type(element))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
